[package]
name = "connector"
version = "0.1.0"
edition = "2024"

[features]
default = ["binancefutures", "bybit", "coinbase"]
binancefutures = []
bybit = []
coinbase = []

[dependencies]
hftbacktest = { path = "../hftbacktest" }
tracing = "0.1.41"
anyhow = "1.0.98"
thiserror = "2.0.12"
bincode = "2.0.1"
chrono = { version = "0.4.41" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140" }
tokio = { version = "1.45.0", features = ["full"] }
tokio-tungstenite = { version = "0.26.2", features = ["rustls-tls-native-roots"] }
reqwest = { version = "0.12.15", default-features = false, features = ["json", "rustls-tls-native-roots"] }
futures-util = { version = "0.3.31" }
sha2 = "0.10.9"
hmac = "0.12.1"
iceoryx2 = { version = "0.6.1", features = ["logger_tracing"] }
toml = "0.8.22"
tracing-subscriber = "0.3.19"
clap = { version = "4.5.38", features = ["derive"] }
hashbrown = "0.15.3"
rand = "0.9.1"
jsonwebtoken = "8"